import { StyleSheet } from 'react-native';

export const previewStyles = StyleSheet.create({
  backdrop: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'transparent',
    zIndex: 999,
  },
  container: {
    position: 'absolute',
    left: 0,
    right: 0, top: 0, bottom: 0,
    zIndex: 1000,
    overflow: 'hidden',
  },
  webViewContainer: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#0a0a0a',
  },
  reloadBanner: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    zIndex: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingLeft: 18,
    paddingRight: 6,
    backgroundColor: 'rgba(16, 20, 28, 0.96)',
    borderRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
    elevation: 12,
  },
  reloadBannerText: {
    color: '#e5e7eb',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  reloadBannerAction: {
    marginLeft: 4,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 22,
    backgroundColor: '#6366F1',
  },
  reloadBannerActionText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
});
