import { StyleSheet, Platform } from 'react-native';
import { AppColors } from '../../../shared/theme/colors';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    marginBottom: 16,
    marginTop: 8, // Add space above each message card
  },
  threadContainer: {
    width: 32,
    alignItems: 'center',
    position: 'relative',
  },
  threadDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#6E7681',
    marginTop: 8,
    zIndex: 2,
  },
  threadLine: {
    position: 'absolute',
    top: 18,
    bottom: -24, // Reduced from -40 to prevent line from extending too far
    width: 2,
    backgroundColor: 'rgba(110, 118, 129, 0.3)',
    zIndex: 1,
  },
  contentContainer: {
    flex: 1,
    overflow: 'hidden', // Prevent content from overflowing horizontally
  },
  userMessageContainer: {
    marginLeft: 0, // No thread container for user messages
  },
  retryToolButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(88,166,255,0.35)',
    backgroundColor: 'rgba(88,166,255,0.12)',
  },
  retryToolButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#58A6FF',
    letterSpacing: -0.1,
  },
  readFileInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
  },
  readFileLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#8B949E',
    letterSpacing: 0.5,
  },
  toolBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(88, 166, 255, 0.3)',
  },
  toolBadgeGlob: {
    backgroundColor: 'rgba(163, 113, 247, 0.15)',
    borderColor: 'rgba(163, 113, 247, 0.3)',
  },
  toolBadgeEdit: {
    backgroundColor: 'rgba(63, 185, 80, 0.15)',
    borderColor: 'rgba(63, 185, 80, 0.3)',
  },
  toolBadgeWrite: {
    backgroundColor: 'rgba(63, 185, 80, 0.15)',
    borderColor: 'rgba(63, 185, 80, 0.3)',
  },
  toolBadgeList: {
    backgroundColor: 'rgba(163, 113, 247, 0.15)',
    borderColor: 'rgba(163, 113, 247, 0.3)',
  },
  toolBadgeTodo: {
    backgroundColor: 'rgba(255, 166, 87, 0.15)',
    borderColor: 'rgba(255, 166, 87, 0.3)',
  },
  toolBadgeWebSearch: {
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
    borderColor: 'rgba(88, 166, 255, 0.3)',
  },
  toolBadgeQuestion: {
    backgroundColor: 'rgba(255, 166, 87, 0.15)',
    borderColor: 'rgba(255, 166, 87, 0.3)',
  },
  toolBadgeCurl: {
    backgroundColor: 'rgba(163, 113, 247, 0.15)',
    borderColor: 'rgba(163, 113, 247, 0.3)',
  },
  toolBadgeAgent: {
    backgroundColor: 'rgba(188, 140, 255, 0.15)',
    borderColor: 'rgba(188, 140, 255, 0.3)',
  },
  toolBadgeSearch: {
    backgroundColor: 'rgba(255, 166, 87, 0.15)',
    borderColor: 'rgba(255, 166, 87, 0.3)',
  },
  toolBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#58A6FF',
    letterSpacing: 0.5,
  },
  readFileName: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  readFileInfo: {
    fontSize: 12,
    color: '#6E7681',
  },
  globStats: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#6E7681',
    marginLeft: 20,
    marginTop: 2,
  },
  writeStatus: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#6E7681',
    marginLeft: 20,
    marginTop: 4,
  },
  executingStatus: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginLeft: 20,
    marginTop: 4,
  },
  globFileList: {
    marginTop: 8,
    marginLeft: 20,
  },
  globFile: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.7)',
    marginBottom: 2,
  },
  // Terminal styles
  terminalCommand: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  terminalPrompt: {
    fontSize: 15,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#00FF88',
    fontWeight: '600',
  },
  terminalText: {
    flex: 1,
    fontSize: 15,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.95)',
    lineHeight: 22,
  },
  terminalOutput: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 20,
    marginBottom: 12,
  },
  terminalOutputLine: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#C9D1D9',
    lineHeight: 20,
    flex: 1,
  },
  addedLine: {
    color: '#3FB950',
    backgroundColor: 'rgba(63, 185, 80, 0.1)',
    paddingLeft: 4,
  },
  removedLine: {
    color: '#F85149',
    backgroundColor: 'rgba(248, 81, 73, 0.1)',
    paddingLeft: 4,
  },
  editHeader: {
    color: '#58A6FF',
    fontWeight: '600',
    marginTop: 4,
  },
  editSubheader: {
    color: '#8B949E',
    fontSize: 12,
    marginBottom: 8,
  },
  editFileHeader: {
    fontSize: 14,
    fontWeight: '600',
    color: '#58A6FF',
    marginBottom: 4,
  },
  editFileStats: {
    fontSize: 12,
    color: '#8B949E',
    marginBottom: 8,
  },
  expandOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 8,
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  showMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1C1C1E',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    zIndex: 10,
  },
  showLessButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  showMoreButtonSimple: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 8,
    paddingVertical: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  showMoreText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#8B949E',
  },
  editCard: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    position: 'relative',
  },
  editContent: {
    padding: 12,
  },
  diffLine: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  lineNumber: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#6E7681',
    minWidth: 40,
    textAlign: 'right',
    paddingRight: 12,
    userSelect: 'none',
  },
  editExpandButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  editExpandText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.5)',
  },
  // File list styles (for LIST tool)
  fileListCard: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    padding: 12,
    marginTop: 8,
  },
  fileListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  fileListName: {
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.8)',
  },
  fileListNameDir: {
    color: '#58A6FF',
    fontWeight: '500',
  },
  // Todo list styles (for TODO tool)
  todoBoard: {
    marginTop: 6,
    backgroundColor: 'rgba(12, 14, 18, 0.65)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 12,
  },
  todoBoardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  todoBoardTitleWrap: {
    flex: 1,
  },
  todoBoardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  todoListCard: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    padding: 0,
    gap: 6,
  },
  todoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  todoItemPending: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  todoItemInProgress: {
    backgroundColor: 'rgba(88, 166, 255, 0.08)',
  },
  todoItemCompletedRow: {
    backgroundColor: 'rgba(63, 185, 80, 0.08)',
  },
  todoItemIconMinimal: {
    width: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoItemIconPill: {
    marginTop: 1,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  todoItemIconPillPending: {
    backgroundColor: 'rgba(154, 164, 178, 0.12)',
    borderColor: 'rgba(154, 164, 178, 0.3)',
  },
  todoItemIconPillProgress: {
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
    borderColor: 'rgba(88, 166, 255, 0.3)',
  },
  todoItemIconPillDone: {
    backgroundColor: 'rgba(63, 185, 80, 0.16)',
    borderColor: 'rgba(63, 185, 80, 0.3)',
  },
  todoContent: {
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.9)',
    flex: 1,
  },
  todoContentCompleted: {
    color: 'rgba(255, 255, 255, 0.5)',
    textDecorationLine: 'line-through',
  },
  // Web search styles
  webSearchStats: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#6E7681',
    marginLeft: 20,
    marginTop: 4,
  },
  webSearchResults: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    padding: 12,
    marginTop: 8,
  },
  webSearchResultItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(30, 30, 30, 0.8)',
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#58A6FF',
  },
  webSearchResultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  webSearchResultTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#58A6FF',
    flex: 1,
  },
  webSearchResultUrl: {
    fontSize: 11,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#6E7681',
    marginBottom: 6,
  },
  webSearchResultSnippet: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 18,
  },
  // Q&A styles (ask_user_question)
  qaList: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    padding: 12,
    marginTop: 8,
  },
  qaItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(30, 30, 30, 0.8)',
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#FFA657',
  },
  qaQuestion: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  qaQuestionText: {
    fontSize: 13,
    color: '#FFA657',
    fontWeight: '600',
    flex: 1,
  },
  qaAnswer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingLeft: 8,
  },
  qaAnswerText: {
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.8)',
    flex: 1,
  },
  // Curl styles
  curlStatus: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: '#6E7681',
    marginLeft: 20,
    marginTop: 4,
  },
  curlOutput: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    padding: 12,
    marginTop: 8,
  },
  curlOutputText: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 18,
  },
  // Agent styles
  agentCard: {
    backgroundColor: '#0d0d0d',
    borderWidth: 1,
    borderColor: 'rgba(188, 140, 255, 0.15)',
    borderRadius: 12,
    padding: 14,
  },
  agentCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  agentCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  agentTypeName: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  agentStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(63, 185, 80, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  agentStatusChipError: {
    backgroundColor: 'rgba(248, 81, 73, 0.12)',
  },
  agentStatusChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#3FB950',
  },
  agentErrorText: {
    fontSize: 12,
    color: '#F85149',
    marginTop: 8,
    lineHeight: 16,
  },
  agentCardDescription: {
    fontSize: 13,
    color: '#9ca3af',
    marginTop: 10,
    lineHeight: 18,
  },
  agentDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginVertical: 10,
  },
  agentResultText: {
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 18,
  },
  agentExpandBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
  },
  agentExpandText: {
    fontSize: 12,
    color: '#6E7681',
  },
  // Bash card styles (terminal command + output grouped)
  // ─── Direct terminal card ───
  termCard: {
    backgroundColor: '#0C0C0C',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
    marginBottom: 12,
  },
  termCardError: {
    borderColor: 'rgba(248, 81, 73, 0.2)',
  },
  termHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#1A1A1A',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  termTrafficLights: {
    flexDirection: 'row',
    gap: 6,
    marginRight: 10,
  },
  termDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  termHeaderTitle: {
    flex: 1,
    fontSize: 11,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.4)',
    fontFamily: Platform.OS === 'ios' ? 'SF Pro Text' : 'sans-serif',
  },
  termBody: {
    padding: 14,
  },
  termPromptLine: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  termPromptChar: {
    color: '#27C93F',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginRight: 8,
    lineHeight: 20,
  },
  termCommandText: {
    flex: 1,
    color: '#E8E8E8',
    fontSize: 13,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 20,
  },
  termOutputText: {
    color: 'rgba(255, 255, 255, 0.55)',
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 18,
    paddingLeft: 20,
  },
  termOutputError: {
    color: '#F85149',
  },
  termShowMore: {
    paddingTop: 8,
    paddingLeft: 20,
  },
  termShowMoreText: {
    color: 'rgba(255, 255, 255, 0.3)',
    fontSize: 11,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  // ─── Agent bash card ───
  bashCard: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    marginBottom: 12,
  },
  bashCardError: {
    backgroundColor: 'rgba(40, 20, 20, 0.95)',
    borderColor: 'rgba(248, 81, 73, 0.3)',
  },
  bashHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  bashTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  expandButton: {
    padding: 4,
  },
  bashContent: {
    padding: 12,
  },
  bashRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bashDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 8,
    marginHorizontal: -12, // Extend to card edges (compensate for bashContent padding)
  },
  bashLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.4)',
    width: 32,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  bashInput: {
    flex: 1,
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 18,
  },
  bashOutput: {
    flex: 1,
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.65)',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 18,
  },
  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 60, // Safe area
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
  },
  closeButton: {
    padding: 8,
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  modalSection: {
    marginBottom: 24,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
    marginBottom: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  modalInput: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 22,
  },
  modalOutput: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.75)',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 20,
  },
  modalDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 24,
  },
  // Minimal professional chat styles
  messageBlock: {
    marginBottom: 4,
  },
  userMessageBlock: {
    marginBottom: 4,
    alignItems: 'flex-end',
  },
  userMessageCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 18,
    borderTopRightRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
    maxWidth: '78%',
    alignSelf: 'flex-end',
  },
  userMessageCardWide: {
    maxWidth: '85%',
  },
  messageImagesContainer: {
    marginBottom: 8,
    gap: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  messageImagesContainerDouble: {
    justifyContent: 'flex-start',
  },
  messageImagesContainerQuad: {
    justifyContent: 'flex-start',
  },
  messageImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  messageImageDouble: {
    width: 90,
    height: 90,
    borderRadius: 10,
  },
  messageImageQuad: {
    width: 100,
    height: 100,
    borderRadius: 10,
  },
  assistantMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 4,
  },
  assistantMessageContent: {
    flex: 1,
    marginTop: 3, // Align text baseline with thread dot center
    overflow: 'hidden', // Prevent markdown content from overflowing
  },
  loadingText: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.5)',
    fontStyle: 'italic',
  },
  // Active thinking (while AI is thinking)
  thinkingActiveContainer: {
    backgroundColor: 'rgba(139, 124, 246, 0.08)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(139, 124, 246, 0.2)',
  },
  thinkingActiveHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  thinkingActiveLabel: {
    fontSize: 14,
    color: AppColors.primary,
    fontWeight: '600',
  },
  thinkingActiveText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.6)',
    fontStyle: 'italic',
    lineHeight: 18,
    flex: 1,
  },
  // Thinking text with phrase rotation
  thinkingShimmerText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.55)',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  // Simple streaming thinking style
  thinkingStreamContainer: {
    paddingVertical: 2,
  },
  thinkingStreamRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  thinkingDotsRow: {
    flexDirection: 'row',
    marginLeft: 1,
  },
  thinkingDotsText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.55)',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  thinkingStreamText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.35)',
    fontStyle: 'italic',
    lineHeight: 20,
    marginBottom: 8,
  },
  // Collapsible thinking (after completion)
  thinkingCollapsible: {
    backgroundColor: 'rgba(139, 124, 246, 0.06)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(139, 124, 246, 0.15)',
  },
  thinkingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  thinkingHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  thinkingHeaderText: {
    fontSize: 12,
    color: 'rgba(139, 124, 246, 0.8)',
    fontWeight: '600',
  },
  thinkingPreviewText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.4)',
    fontStyle: 'italic',
    marginTop: 6,
    lineHeight: 16,
  },
  thinkingExpandedText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.6)',
    fontStyle: 'italic',
    marginTop: 10,
    lineHeight: 18,
  },
  // Long-press context menu (liquid glass)
  menuOverlay: {
    flex: 1,
  },
  menuCard: {
    alignSelf: 'flex-end',
    borderRadius: 16,
    marginVertical: 6,
    minWidth: 150,
    zIndex: 100,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 12,
  },
  menuCardInner: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  menuTime: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.45)',
    fontWeight: '500',
    paddingHorizontal: 14,
    paddingBottom: 8,
    marginBottom: 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 10,
  },
  menuItemText: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '500',
  },
  outputCopyButton: {
    padding: 4,
    marginLeft: 6,
  },
  // Cost indicator styles
  costIndicator: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 0,
  },
  tokenBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  costText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.35)',
    fontWeight: '500',
  },
  copiedFeedback: {
    fontSize: 10,
    color: '#3FB950',
    fontWeight: '500',
    textAlign: 'right',
    marginTop: 4,
  },
  // Legacy styles (kept for compatibility)
  thinkingContainer: {
    marginTop: 8,
    marginBottom: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  thinkingLabel: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.4)',
    fontWeight: '600',
    marginBottom: 6,
  },
  thinkingText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.35)',
    fontStyle: 'italic',
    lineHeight: 20,
    marginTop: 4,
  },
  userName: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
    marginBottom: 4,
    textAlign: 'right',
  },
  assistantName: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
    textAlign: 'left',
  },
  errorName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#E85D75',
    marginBottom: 4,
  },
  userMessage: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.95)',
    lineHeight: 22,
    fontWeight: '400',
  },
  assistantMessage: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.85)',
    lineHeight: 22,
    fontWeight: '400',
    textAlign: 'left',
  },
  errorMessage: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 20,
    fontWeight: '400',
  },
  systemBlock: {
    paddingVertical: 4,
  },
  systemText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.5)',
    textAlign: 'left',
    fontWeight: '400',
  },
  // Project created card
  projectCreatedCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 20,
    paddingTop: 28,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.15)',
    overflow: 'hidden',
    alignItems: 'center',
  },
  projectCreatedGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 100,
  },
  projectCreatedIconBox: {
    marginBottom: 14,
  },
  projectCreatedIconGradient: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  projectCreatedTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#10B981',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  projectCreatedName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 14,
    letterSpacing: -0.3,
  },
  projectCreatedTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 20,
  },
  projectCreatedTagText: {
    fontSize: 12,
    fontWeight: '600',
  },
  projectCreatedDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginBottom: 14,
    alignSelf: 'stretch',
  },
  projectCreatedHint: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.35)',
  },
  // Loading card styles (same as bash card)
  loadingCard: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    marginBottom: 12,
  },
  loadingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  loadingTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  loadingBody: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  loadingLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(139, 124, 246, 0.6)',
    letterSpacing: 0.5,
    width: 48,
    flexShrink: 0,
  },
  loadingStatus: {
    flex: 1,
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    color: 'rgba(139, 124, 246, 0.9)',
    lineHeight: 18,
  },
  // Backend Log styles
  backendLogBlock: {
    backgroundColor: 'rgba(30, 35, 45, 0.6)',
    borderRadius: 8,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#58A6FF',
  },
  backendLogHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  backendLogLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#58A6FF',
    letterSpacing: 0.5,
    flex: 1,
  },
  backendLogTime: {
    fontSize: 10,
    color: '#8B949E',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  backendLogText: {
    fontSize: 12,
    color: '#C9D1D9',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 18,
  },
  // Plan Approval Styles
  planApprovalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
  },
  planApprovalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
  },
  planApprovalButtonReject: {
    backgroundColor: 'rgba(248, 81, 73, 0.15)',
  },
  planApprovalButtonApprove: {
    backgroundColor: AppColors.primary,
  },
  planApprovalButtonText: {
    fontSize: 13,
    fontWeight: '600',
  },
  planApprovalStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  planApprovalStatusText: {
    fontSize: 13,
    fontWeight: '500',
  },
});
