/**
 * Drape Backend - Helper Utilities
 * Common helper functions used across the application
 */

const os = require('os');
const path = require('path');
const fs = require('fs').promises;
const { exec } = require('child_process');
const { promisify } = require('util');

const execAsync = promisify(exec);

/**
 * Get local network IP address
 * Prioritizes WiFi interfaces, falls back to Ethernet
 */
function getLocalIP() {
    const interfaces = os.networkInterfaces();

    // Priority order for interface names
    const priorities = ['en0', 'en1', 'eth0', 'wlan0', 'Wi-Fi'];

    for (const name of priorities) {
        const iface = interfaces[name];
        if (iface) {
            const ipv4 = iface.find(i => i.family === 'IPv4' && !i.internal);
            if (ipv4) return ipv4.address;
        }
    }

    // Fallback: find any external IPv4
    for (const name of Object.keys(interfaces)) {
        const iface = interfaces[name];
        const ipv4 = iface.find(i => i.family === 'IPv4' && !i.internal);
        if (ipv4) return ipv4.address;
    }

    return '127.0.0.1';
}

/**
 * Clean workspace name for Coder
 * Must start with letter, lowercase, alphanumeric and dashes only
 */
function cleanWorkspaceName(name) {
    let clean = name
        .toLowerCase()
        .replace(/[^a-z0-9-]/g, '-')
        .replace(/^[^a-z]+/, '')
        .replace(/-+/g, '-')
        .replace(/-$/, '')
        .substring(0, 32);

    if (!clean || !/^[a-z]/.test(clean)) {
        clean = 'ws-' + Date.now().toString(36);
    }

    return clean;
}

/**
 * Clean project ID (remove ws- prefix if present)
 */
function cleanProjectId(projectId) {
    return projectId.startsWith('ws-') ? projectId.substring(3) : projectId;
}

/**
 * Get repository path for a project
 */
function getRepoPath(projectId) {
    const cleanId = cleanProjectId(projectId);
    return path.join(__dirname, '..', 'cloned_repos', cleanId);
}

/**
 * Unescape special characters in strings
 */
function unescapeString(str) {
    return str
        .replace(/\\n/g, '\n')
        .replace(/\\t/g, '\t')
        .replace(/\\r/g, '\r')
        .replace(/\\"/g, '"')
        .replace(/\\'/g, "'")
        .replace(/\\\\/g, '\\');
}

/**
 * Parse .env file content
 */
function parseEnvContent(content) {
    const vars = {};
    const lines = content.split('\n');

    for (const line of lines) {
        const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/i);
        if (match) {
            let value = match[2];
            // Remove surrounding quotes if present
            if ((value.startsWith('"') && value.endsWith('"')) ||
                (value.startsWith("'") && value.endsWith("'"))) {
                value = value.slice(1, -1);
            }
            vars[match[1]] = value;
        }
    }

    return vars;
}

/**
 * Generate .env file content from object
 */
function generateEnvContent(vars, header = '# Environment variables\n# Generated by Drape IDE\n\n') {
    let content = header;

    for (const [key, value] of Object.entries(vars)) {
        const needsQuotes = /[\s#=]/.test(value);
        const quotedValue = needsQuotes ? `"${value}"` : value;
        content += `${key}=${quotedValue}\n`;
    }

    return content;
}

/**
 * Detect if command is a dev server command
 */
function isDevServerCommand(command) {
    const patterns = [
        /npm\s+(run\s+)?dev/,
        /npm\s+start/,
        /yarn\s+(run\s+)?dev/,
        /yarn\s+start/,
        /ng\s+serve/,
        /gatsby\s+develop/,
        /vite/,
        /next\s+dev/,
        /nuxt\s+dev/,
        /expo\s+start/,
        /flask\s+run/,
        /uvicorn/,
        /rails\s+server/,
        /php\s+artisan\s+serve/,
        /python.*http\.server/,
        /python.*manage\.py\s+runserver/
    ];

    return patterns.some(pattern => pattern.test(command));
}

/**
 * Detect preview URL from command output
 */
function detectPreviewUrl(output, command = '') {
    if (!output) return null;

    const patterns = [
        // Expo tunnel URLs (highest priority)
        /exp:\/\/[^\s]+/,
        /https?:\/\/[a-z0-9-]+\.exp\.direct[^\s]*/,
        /https?:\/\/[a-z0-9-]+\.ngrok\.[^\s]*/,

        // Network URLs (preferred over localhost)
        /Network:\s+(https?:\/\/[^\s]+)/,
        /On Your Network:\s+(https?:\/\/[^\s]+)/,

        // Explicit URLs with ports
        /https?:\/\/\d+\.\d+\.\d+\.\d+:\d+/,

        // Local URLs with labels
        /Local:\s+(https?:\/\/[^\s]+)/,

        // Raw localhost/IP patterns
        /https?:\/\/localhost:\d+/,
        /https?:\/\/127\.0\.0\.1:\d+/,
        /https?:\/\/0\.0\.0\.0:\d+/,

        // Port-only patterns (add http://)
        /(?:at\s+|running\s+(?:at\s+)?|started\s+on\s+)?(?:http:\/\/)?localhost:(\d+)/i,
        /(?:at\s+|running\s+(?:at\s+)?|started\s+on\s+)?(?:http:\/\/)?0\.0\.0\.0:(\d+)/i,
        /(?:at\s+|running\s+(?:at\s+)?|started\s+on\s+)?(?:http:\/\/)?127\.0\.0\.1:(\d+)/i
    ];

    for (const pattern of patterns) {
        const match = output.match(pattern);
        if (match) {
            let url = match[1] || match[0];

            // If it's just a port number, construct full URL
            if (/^\d+$/.test(url)) {
                url = `http://0.0.0.0:${url}`;
            }

            // Add http:// if missing
            if (!url.startsWith('http') && !url.startsWith('exp://')) {
                url = `http://${url}`;
            }

            // Normalize localhost URLs to 0.0.0.0 for network access
            if (url.includes('localhost') || url.includes('127.0.0.1')) {
                const portMatch = url.match(/:(\d+)/);
                if (portMatch) {
                    url = `http://0.0.0.0:${portMatch[1]}`;
                }
            }

            return url;
        }
    }

    return null;
}

/**
 * Convert local URL to public/network URL
 */
function convertToPublicUrl(url, localIP = null) {
    if (!url) return null;

    // Get local IP if not provided
    const ip = localIP || getLocalIP();

    // Don't convert tunnel URLs
    if (url.includes('.ngrok.') || url.includes('.exp.direct') || url.startsWith('exp://')) {
        return url;
    }

    // Convert 0.0.0.0/localhost/127.0.0.1 to local network IP
    return url
        .replace('0.0.0.0', ip)
        .replace('localhost', ip)
        .replace('127.0.0.1', ip);
}

/**
 * Build Coder app URL
 */
function buildCoderAppUrl(baseUrl, username, workspaceName, appName, path = '/') {
    return `${baseUrl}/@${username}/${workspaceName}/apps/${appName}${path}`;
}

/**
 * Wait for a specified time
 */
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Retry a function with exponential backoff
 */
async function retryWithBackoff(fn, maxRetries = 3, baseDelay = 1000) {
    let lastError;

    for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
            return await fn();
        } catch (error) {
            lastError = error;

            if (attempt < maxRetries - 1) {
                const delay = baseDelay * Math.pow(2, attempt);
                console.log(`Retry attempt ${attempt + 1}/${maxRetries} after ${delay}ms...`);
                await sleep(delay);
            }
        }
    }

    throw lastError;
}

/**
 * Check if a file exists
 */
async function fileExists(filePath) {
    try {
        await fs.access(filePath);
        return true;
    } catch {
        return false;
    }
}

/**
 * Read JSON file safely
 */
async function readJsonFile(filePath) {
    try {
        const content = await fs.readFile(filePath, 'utf8');
        return JSON.parse(content);
    } catch {
        return null;
    }
}

/**
 * Truncate string to max length with ellipsis
 */
function truncate(str, maxLength = 100) {
    if (!str || str.length <= maxLength) return str;
    return str.substring(0, maxLength - 3) + '...';
}

/**
 * Generate a simple unique ID
 */
function generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}

module.exports = {
    getLocalIP,
    cleanWorkspaceName,
    cleanProjectId,
    getRepoPath,
    unescapeString,
    parseEnvContent,
    generateEnvContent,
    isDevServerCommand,
    detectPreviewUrl,
    convertToPublicUrl,
    buildCoderAppUrl,
    sleep,
    retryWithBackoff,
    fileExists,
    readJsonFile,
    truncate,
    generateId,
    execAsync
};

