import { StyleSheet } from 'react-native';
import { AppColors } from '../../shared/theme/colors';

const DATE_WHEEL_ITEM_HEIGHT = 44;
const DATE_WHEEL_VISIBLE_ITEMS = 5;
const DATE_WHEEL_PADDING = (DATE_WHEEL_ITEM_HEIGHT * (DATE_WHEEL_VISIBLE_ITEMS - 1)) / 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0F',
  },
  blurOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 5,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  // Branding
  brandingSection: {
    alignItems: 'center',
    marginTop: 40,
  },
  brandName: {
    fontSize: 54,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -1.6,
    marginTop: 16,
  },
  tagline: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.55)',
    marginTop: 12,
    fontWeight: '500',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  // Modal
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  modal: {
    marginHorizontal: 16,
    marginBottom: 90,
    borderRadius: 28,
    overflow: 'hidden',
  },
  modalBlur: {
    flex: 1,
    borderRadius: 28,
  },
  liquidGlassModal: {
    flex: 1,
    borderRadius: 28,
    overflow: 'hidden',
  },
  androidModalBg: {
    flex: 1,
    borderRadius: 28,
    backgroundColor: 'rgba(18, 14, 35, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  modalContent: {
    flex: 1,
    padding: 24,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  initialButtons: {
    flex: 1,
    justifyContent: 'center',
    gap: 12,
  },
  primaryButton: {
    borderRadius: 28,
    overflow: 'hidden',
  },
  primaryButtonGradient: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#fff',
  },
  secondaryButton: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
  },
  formContent: {
    flex: 1,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  glassBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  backButtonInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glassInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 25,
    paddingHorizontal: 18,
    marginBottom: 12,
    height: 50,
    overflow: 'hidden',
  },
  formTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 16,
  },
  errorText: {
    flex: 1,
    fontSize: 13,
    color: '#EF4444',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 25,
    paddingHorizontal: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  input: {
    flex: 1,
    height: 50,
    fontSize: 15,
    color: '#fff',
    marginLeft: 10,
  },
  datePickerTrigger: {
    flex: 1,
    height: 50,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  datePickerText: {
    fontSize: 15,
    color: '#fff',
  },
  datePickerPlaceholder: {
    color: 'rgba(255,255,255,0.3)',
  },
  forgotLink: {
    alignSelf: 'flex-end',
    marginBottom: 16,
    marginTop: 4,
  },
  forgotLinkText: {
    fontSize: 13,
    color: AppColors.primary,
    fontWeight: '500',
  },
  submitButton: {
    height: 52,
    borderRadius: 26,
    backgroundColor: AppColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  switchMode: {
    alignItems: 'center',
    marginTop: 16,
  },
  switchModeText: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.5)',
  },
  switchModeLink: {
    color: AppColors.primary,
    fontWeight: '600',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingVertical: 12,
    zIndex: 10,
  },
  footerText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.3)',
  },
  footerLink: {
    color: AppColors.primary,
  },
  // Apple Sign In & Divider
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 4,
  },
  dividerRowSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  dividerText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.35)',
    marginHorizontal: 12,
  },
  appleButton: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 26,
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    gap: 10,
  },
  appleButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  appleButtonSmall: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    gap: 8,
  },
  appleButtonTextSmall: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  verifyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  verifyFlow: {
    justifyContent: 'center',
    transform: [{ translateY: -18 }],
  },
  verifyContentBlock: {
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 18,
  },
  verifyIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(124, 58, 237, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  verifyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 10,
  },
  verifyMessage: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.5)',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 12,
  },
  verifyStatusText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
  },
  verifyStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  resendButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    marginBottom: 14,
  },
  resendButtonSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: 'rgba(16, 185, 129, 0.2)',
  },
  resendButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
  },
  // GDPR: ToS checkbox styles
  tosRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 12,
    marginTop: 4,
    paddingHorizontal: 4,
  },
  tosCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.25)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  tosCheckboxChecked: {
    backgroundColor: AppColors.primary,
    borderColor: AppColors.primary,
  },
  tosText: {
    flex: 1,
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.5)',
    lineHeight: 18,
  },
  tosLink: {
    color: AppColors.primary,
    textDecorationLine: 'underline' as const,
  },
  // GDPR: Parental notice styles
  parentalNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.2)',
  },
  parentalNoticeText: {
    flex: 1,
    fontSize: 12,
    color: '#F59E0B',
    lineHeight: 17,
  },
  datePickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  datePickerSheet: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: 'rgba(21, 16, 38, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(145,119,255,0.22)',
    borderBottomWidth: 0,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  datePickerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    flex: 1,
  },
  datePickerToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  datePickerToolbarButton: {
    minWidth: 70,
    paddingVertical: 10,
  },
  datePickerToolbarSecondaryText: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.68)',
    fontWeight: '500',
  },
  datePickerToolbarPrimaryText: {
    fontSize: 16,
    color: AppColors.primary,
    fontWeight: '700',
    textAlign: 'right',
  },
  datePickerColumns: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  dateWheelColumn: {
    flex: 1,
  },
  dateWheelLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.42)',
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: 0.8,
  },
  dateWheelFrame: {
    height: DATE_WHEEL_ITEM_HEIGHT * DATE_WHEEL_VISIBLE_ITEMS,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.035)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    position: 'relative',
  },
  dateWheelSelectionBand: {
    position: 'absolute',
    left: 8,
    right: 8,
    top: DATE_WHEEL_PADDING,
    height: DATE_WHEEL_ITEM_HEIGHT,
    borderRadius: 16,
    backgroundColor: 'rgba(109, 76, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(139,111,255,0.38)',
    zIndex: 2,
  },
  dateWheelFadeTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: DATE_WHEEL_PADDING,
    zIndex: 3,
  },
  dateWheelFadeBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: DATE_WHEEL_PADDING,
    zIndex: 3,
  },
  dateWheelScroll: {
    flex: 1,
  },
  dateWheelContent: {
    paddingVertical: DATE_WHEEL_PADDING,
  },
  dateWheelItem: {
    height: DATE_WHEEL_ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  dateWheelItemText: {
    fontSize: 20,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.35)',
  },
  dateWheelItemTextActive: {
    color: '#fff',
  },
  datePickerPreview: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 18,
    letterSpacing: 0.6,
  },
});
