/**
 * Provision Drape Cloud for a newly created project.
 *
 * - Issues an API key
 * - Writes SDK files (drape-cloud.js + drape-cloud.d.ts) into the
 *   generated project
 * - Writes env/config entries depending on the technology
 *
 * Called from the creation pipeline right before the generation
 * phase when `useDrapeCloud: true` is present in creation-input.json.
 */

import fs from 'fs/promises';
import path from 'path';
import { config } from '../../config';
import { fileService } from '../file.service';
import { log } from '../../utils/logger';
import { issueApiKey } from './api-key.service';
import type { ProjectTechnology } from '../project-technology';
import {
  inferDataModelWithLLM,
  renderDataModelMarkdown,
  renderSeedSkeleton,
  type DataModelPlan,
} from './feature-to-tables';
import { writeBaseline } from './declared-tables.service';

const SDK_SOURCE_DIR = path.join(__dirname, 'sdk');

async function loadSdkFile(name: string): Promise<string> {
  const p = path.join(SDK_SOURCE_DIR, name);
  return fs.readFile(p, 'utf8');
}

/**
 * Compute the public Drape Cloud base URL the generated app will
 * hit. In dev this is https://dev.drape.info/v1, in prod drape.info.
 * Falls back to localhost when nothing is configured so local `npm
 * run dev` still works.
 */
function publicApiUrl(): string {
  const base = config.publicUrl || `http://localhost:${config.port}`;
  return base.replace(/\/+$/, '') + '/v1';
}

/**
 * Given a technology, decide where the SDK lives in the project.
 * Next.js: app/lib/drape-cloud.js
 * React (Vite): src/lib/drape-cloud.js
 * Vue: src/lib/drape-cloud.js
 * Astro: src/lib/drape-cloud.js
 * Expo: lib/drape-cloud.js
 * HTML: drape-cloud.js (root)
 */
function sdkTargetDir(tech: ProjectTechnology): string {
  // Must match the tsconfig "@/lib/*" alias declared in each template.
  // Next.js templates map @/lib/* to ./lib/* (NOT ./app/lib/*), so the
  // SDK has to live in the project root, not under app/.
  switch (tech) {
    case 'nextjs':
      return 'lib';
    case 'html':
      return '.';
    case 'expo':
      return 'lib';
    default:
      return 'src/lib';
  }
}

function envFileFor(tech: ProjectTechnology): { name: string; contents: (apiUrl: string, key: string) => string } {
  switch (tech) {
    case 'nextjs':
      return {
        name: '.env.local',
        contents: (apiUrl, key) =>
          `NEXT_PUBLIC_DRAPE_CLOUD_API_URL=${apiUrl}\nNEXT_PUBLIC_DRAPE_CLOUD_KEY=${key}\n`,
      };
    case 'expo':
      return {
        name: '.env.local',
        contents: (apiUrl, key) =>
          `EXPO_PUBLIC_DRAPE_CLOUD_API_URL=${apiUrl}\nEXPO_PUBLIC_DRAPE_CLOUD_KEY=${key}\n`,
      };
    case 'html':
      // HTML templates can't read .env at runtime — bake into a tiny JS config file.
      return {
        name: 'drape-cloud-config.js',
        contents: (apiUrl, key) =>
          `// Generated by Drape Cloud provisioning. Do not edit.\nwindow.__DRAPE_CLOUD__ = ${JSON.stringify({ apiUrl, projectKey: key })};\n`,
      };
    default:
      // Vite / Astro / Vue / Svelte / Remix / Nuxt / Solid / Angular → VITE_ prefix works for all Vite-based
      return {
        name: '.env.local',
        contents: (apiUrl, key) =>
          `VITE_DRAPE_CLOUD_API_URL=${apiUrl}\nVITE_DRAPE_CLOUD_KEY=${key}\n`,
      };
  }
}

export interface ProvisionResult {
  apiKey: string;
  apiUrl: string;
  sdkPath: string;
  envFile: string;
  /** The baseline data-model plan derived from creation-input.json. */
  dataModel: DataModelPlan;
}

export async function provisionDrapeCloudForProject(
  projectId: string,
  userId: string,
  tech: ProjectTechnology,
  opts: {
    description?: string | null;
    structuredAnswers?: Record<string, unknown> | null;
    projectTitle?: string;
  } = {},
): Promise<ProvisionResult> {
  const key = await issueApiKey(projectId, userId);
  const apiUrl = publicApiUrl();

  // Copy SDK files into the project
  const targetDir = sdkTargetDir(tech);
  const sdkJs = await loadSdkFile('drape-cloud.js');
  const sdkDts = await loadSdkFile('drape-cloud.d.ts');
  const sdkPath = `${targetDir}/drape-cloud.js`;
  await fileService.writeFile(projectId, sdkPath, sdkJs);
  if (tech !== 'html') {
    await fileService.writeFile(projectId, `${targetDir}/drape-cloud.d.ts`, sdkDts);
  }

  // Write env/config file
  const env = envFileFor(tech);
  await fileService.writeFile(projectId, env.name, env.contents(apiUrl, key.key));

  // Baseline data-model: LLM-inferred from description + structuredAnswers
  // and persisted BEFORE generation runs. The AI finds it in the workspace
  // and treats it as the schema it must implement. Falls back to the
  // deterministic keyword mapper if the LLM call fails.
  const plan = await inferDataModelWithLLM({
    description: opts.description,
    structuredAnswers: opts.structuredAnswers,
  });
  await fileService.writeFile(
    projectId,
    '.drape/data-model.md',
    renderDataModelMarkdown(plan, { projectTitle: opts.projectTitle }),
  );
  // Persist the baseline as the authoritative list of declared tables.
  // The `declare_tables` tool will mutate this file; the write_file
  // validator reads it to catch drape.table('x') references to tables
  // that weren't declared first.
  await writeBaseline(projectId, plan.tables, { projectTitle: opts.projectTitle });
  // Seed skeleton — AI later fills the arrays with realistic rows.
  const seedSkeleton = renderSeedSkeleton(plan);
  if (Object.keys(seedSkeleton).length > 0) {
    await fileService.writeFile(
      projectId,
      '.drape/cloud-seed.json',
      JSON.stringify(seedSkeleton, null, 2),
    );
  }

  log.info(
    `[DrapeCloud] provisioned project ${projectId} (${tech}) → key=${key.key.slice(0, 12)}... ` +
      `sdk=${sdkPath} baseline=${plan.tables.length} tables (${plan.tables.map((t) => t.name).join(', ')})`,
  );
  return { apiKey: key.key, apiUrl, sdkPath, envFile: env.name, dataModel: plan };
}
