-- ================================================================
-- Drape Cloud — multi-tenant shared backend schema.
--
-- Single shared Postgres DB hosts data for ALL projects that opt
-- into cloud mode. Isolation is logical, not physical: every row
-- carries a project_id, and the API layer enforces a scoped query
-- helper that injects project_id = $1 on every read/write.
--
-- Tables are intentionally simple:
-- - drape_api_keys   : one key per project, used by the generated
--                      frontend to authenticate as "this project"
-- - drape_rows       : the actual application data — jsonb payload
--                      keyed by (project_id, table_name, id)
-- - drape_end_users  : users of a GENERATED app (not Drape users)
-- - drape_sessions   : opaque session tokens for end-user auth
--
-- All timestamps are TIMESTAMPTZ. All ids are UUIDs generated by
-- the DB so the client never trusts a user-supplied id.
-- ================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------- drape_api_keys ----------
-- One or more API keys per project. The key is a random 32-byte
-- hex string stored as plain text (it's a bearer token — the
-- client has to send it as-is over HTTPS). Revocation is a simple
-- DELETE on this table. drape_project_id and drape_user_id are
-- the ids from the Drape platform (Firebase uids), not Postgres
-- uuids, so they're TEXT.
CREATE TABLE IF NOT EXISTS drape_api_keys (
  key          TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL,
  user_id      TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_drape_api_keys_project ON drape_api_keys(project_id);

-- ---------- drape_rows ----------
-- Every application row lives here. table_name is a logical label
-- chosen by the generated app (e.g. "movies", "tasks"). end_user_id
-- is nullable: some data belongs to "the app" (public seed data),
-- some belongs to a specific signed-in user. The API enforces the
-- project_id filter — there is no path that can read another
-- project's rows.
CREATE TABLE IF NOT EXISTS drape_rows (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   TEXT NOT NULL,
  table_name   TEXT NOT NULL CHECK (char_length(table_name) BETWEEN 1 AND 64),
  end_user_id  UUID,
  data         JSONB NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hot path: list rows of a table within a project
CREATE INDEX IF NOT EXISTS idx_drape_rows_scope
  ON drape_rows(project_id, table_name, created_at DESC);

-- User-scoped data (e.g. "my favorites"): the app often wants
-- "rows for THIS logged-in user"
CREATE INDEX IF NOT EXISTS idx_drape_rows_user_scope
  ON drape_rows(project_id, table_name, end_user_id)
  WHERE end_user_id IS NOT NULL;

-- ---------- drape_end_users ----------
-- Users of the generated apps. Scoped per-project: the same email
-- can exist in two different projects with two different accounts.
-- password_hash is bcrypt (12 rounds). anonymous_id is the cookie
-- id created on first SDK use; when the user signs up, we keep it
-- so their anonymous data migrates into the account.
CREATE TABLE IF NOT EXISTS drape_end_users (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id     TEXT NOT NULL,
  email          TEXT,
  password_hash  TEXT,
  display_name   TEXT,
  is_anonymous   BOOLEAN NOT NULL DEFAULT false,
  anonymous_id   TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Signed-in lookup: per-project unique email (allow NULL for anon)
CREATE UNIQUE INDEX IF NOT EXISTS uq_drape_end_users_project_email
  ON drape_end_users(project_id, lower(email))
  WHERE email IS NOT NULL;

-- Anon re-hydration: look up by anon cookie within a project
CREATE UNIQUE INDEX IF NOT EXISTS uq_drape_end_users_project_anon
  ON drape_end_users(project_id, anonymous_id)
  WHERE anonymous_id IS NOT NULL;

-- ---------- drape_sessions ----------
-- Opaque session tokens. Each row = one active session. The token
-- column is the 32-byte random hex string the client holds. We
-- never issue JWTs — revoking a session is just a DELETE here.
CREATE TABLE IF NOT EXISTS drape_sessions (
  token        TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL,
  end_user_id  UUID NOT NULL REFERENCES drape_end_users(id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at   TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_drape_sessions_user ON drape_sessions(end_user_id);
CREATE INDEX IF NOT EXISTS idx_drape_sessions_expiry ON drape_sessions(expires_at);

-- ---------- drape_quota_usage ----------
-- Per-project aggregate of row count + monthly request count, for
-- quota enforcement. Updated by triggers on drape_rows + by the
-- request middleware.
CREATE TABLE IF NOT EXISTS drape_quota_usage (
  project_id      TEXT PRIMARY KEY,
  row_count       BIGINT NOT NULL DEFAULT 0,
  requests_month  BIGINT NOT NULL DEFAULT 0,
  month_anchor    TIMESTAMPTZ NOT NULL DEFAULT date_trunc('month', now()),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ================================================================
-- Platform tables (Explore / analytics / custom domains).
-- These are platform-level concerns — they describe the published
-- sites managed by Drape itself, not the data inside the generated
-- apps. Project metadata (slug, owner, public flag, title, etc.)
-- still lives in Firestore (`published_sites`); Postgres is used
-- here only for high-frequency append-only data (page views) and
-- for relational lookups that Firestore is bad at (custom domain
-- → slug mapping for the request hot path).
-- ================================================================

-- ---------- drape_published_views ----------
-- One row per page view of a published site. Append-only. We
-- aggregate at read time for analytics (cheap up to ~1M rows; can
-- migrate to a rollup table later).
-- visitor_hash = sha256(ip + user_agent + day) so we can compute
-- "unique visitors per day" without storing raw IPs.
CREATE TABLE IF NOT EXISTS drape_published_views (
  id            BIGSERIAL PRIMARY KEY,
  slug          TEXT NOT NULL,
  project_id    TEXT NOT NULL,
  visitor_hash  TEXT NOT NULL,
  country       TEXT,
  referrer      TEXT,
  path          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_drape_published_views_slug_created
  ON drape_published_views(slug, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drape_published_views_project_created
  ON drape_published_views(project_id, created_at DESC);
-- Unique-per-day visitor dedupe: same hash within the same day
-- counts once. Matches how visitor_hash is salted (per-day).
CREATE UNIQUE INDEX IF NOT EXISTS uq_drape_published_views_dedupe
  ON drape_published_views(slug, visitor_hash, date_trunc('day', created_at));

-- ---------- drape_custom_domains ----------
-- Maps a custom domain (e.g. mio-negozio.com) to a published slug.
-- status:
--   pending  : created, DNS not verified yet
--   verified : DNS CNAME confirmed, cert provisioning in progress
--   active   : cert issued, requests served
--   failed   : verification timed out or cert provisioning failed
-- Lookup is on the request hot path (every incoming request to a
-- custom domain), so we keep this in Postgres with a covering
-- index by domain.
CREATE TABLE IF NOT EXISTS drape_custom_domains (
  domain        TEXT PRIMARY KEY,
  project_id    TEXT NOT NULL,
  slug          TEXT NOT NULL,
  user_id       TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  last_check_at TIMESTAMPTZ,
  last_error    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  verified_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_drape_custom_domains_project ON drape_custom_domains(project_id);
CREATE INDEX IF NOT EXISTS idx_drape_custom_domains_user ON drape_custom_domains(user_id);

-- ---------- drape_project_versions ----------
-- One row per publish. Each row references a tarball on disk
-- (snapshot of the built static site at publish time). Used for
-- rollback: "republish version N" copies that tarball back to the
-- published directory. We keep at most 10 versions per project
-- (older ones pruned by the publish flow).
CREATE TABLE IF NOT EXISTS drape_project_versions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id      TEXT NOT NULL,
  slug            TEXT NOT NULL,
  user_id         TEXT NOT NULL,
  version_number  INT NOT NULL,
  snapshot_path   TEXT NOT NULL,
  size_bytes      BIGINT,
  message         TEXT,
  is_active       BOOLEAN NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_drape_project_versions_project_created
  ON drape_project_versions(project_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_drape_project_versions_project_number
  ON drape_project_versions(project_id, version_number);
